import requests

tenant_id = 'd3507aa4-c917-4edd-b4ca-154078b855e1'
client_id = '9a272fba-c031-492e-bc9f-daeb4df9e448'
client_secret = 'JhO8Q~Wpx0tGaEjH~cEDAhrhHBCj0Fk-hZ~7.amo'
scope = 'https://graph.microsoft.com/.default'

url = f'https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token'
data = {
    'grant_type': 'client_credentials',
    'client_id': client_id,
    'client_secret': client_secret,
    'scope': scope
}


# https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-reports#code-try-0
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjVCM25SeHRRN2ppOGVORGMzRnkwNUtmOTdaRSIsImtpZCI6IjVCM25SeHRRN2ppOGVORGMzRnkwNUtmOTdaRSJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDM1MDdhYTQtYzkxNy00ZWRkLWI0Y2EtMTU0MDc4Yjg1NWUxLyIsImlhdCI6MTcwNDIwMzgzNywibmJmIjoxNzA0MjAzODM3LCJleHAiOjE3MDQyMDg5MTcsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84VkFBQUFLKyt4U0JpTVVKRk1SNkZKS2xubnJlNFphMmYzTmlaR21qZTRsMDh5WERBNDk4c2thN1pIV3BLK3ExZE1aUnY4bEFDMHREYlJKQlZCSFpCdWpIb0kzSllLSVVvSFpPQVQzU3hqUDdvdWgyZz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMThmYmNhMTYtMjIyNC00NWY2LTg1YjAtZjdiZjJiMzliM2YzIiwiYXBwaWRhY3IiOiIwIiwiZGV2aWNlaWQiOiI2ODAxYTRlNy1mYzUwLTQ4YjktYmJhMC00YjUyZDYyZWY0MWUiLCJmYW1pbHlfbmFtZSI6IlNhd3llciIsImdpdmVuX25hbWUiOiJTdGV2ZSIsImlwYWRkciI6IjgyLjY4LjExNy42MiIsIm5hbWUiOiJTdGV2ZSBTYXd5ZXIiLCJvaWQiOiI4NjljNDY3YS01MmJjLTRkNzctYWVlYy1hNTZiYTFjZGVlNmYiLCJwdWlkIjoiMTAwM0JGRkQ4REUxMTVEMiIsInJoIjoiMC5BUXNBcEhwUTB4ZkozVTYweWhWQWVMaFY0UWtBQUFBQUFBQUF3QUFBQUFBQUFBQUxBS2MuIiwic2NwIjoiQXBwLlJlYWQuQWxsIENhcGFjaXR5LlJlYWQuQWxsIENhcGFjaXR5LlJlYWRXcml0ZS5BbGwgQ29udGVudC5DcmVhdGUgRGFzaGJvYXJkLlJlYWQuQWxsIERhc2hib2FyZC5SZWFkV3JpdGUuQWxsIERhdGFmbG93LlJlYWQuQWxsIERhdGFmbG93LlJlYWRXcml0ZS5BbGwgRGF0YXNldC5SZWFkLkFsbCBEYXRhc2V0LlJlYWRXcml0ZS5BbGwgR2F0ZXdheS5SZWFkLkFsbCBHYXRld2F5LlJlYWRXcml0ZS5BbGwgSXRlbS5FeGVjdXRlLkFsbCBJdGVtLlJlYWRXcml0ZS5BbGwgSXRlbS5SZXNoYXJlLkFsbCBQaXBlbGluZS5EZXBsb3kgUGlwZWxpbmUuUmVhZC5BbGwgUGlwZWxpbmUuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZC5BbGwgUmVwb3J0LlJlYWRXcml0ZS5BbGwgU3RvcmFnZUFjY291bnQuUmVhZC5BbGwgU3RvcmFnZUFjY291bnQuUmVhZFdyaXRlLkFsbCBUZW5hbnQuUmVhZC5BbGwgVGVuYW50LlJlYWRXcml0ZS5BbGwgVXNlclN0YXRlLlJlYWRXcml0ZS5BbGwgV29ya3NwYWNlLlJlYWQuQWxsIFdvcmtzcGFjZS5SZWFkV3JpdGUuQWxsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiQ0Z1M1Y1TVdOaERleHltVHZmWjV1LU91UW1BcDh2U2NMbHBhRmdRc2F0dyIsInRpZCI6ImQzNTA3YWE0LWM5MTctNGVkZC1iNGNhLTE1NDA3OGI4NTVlMSIsInVuaXF1ZV9uYW1lIjoiYWRtaW5AWW9ya3RlY2hTb2x1dGlvbnNMdGQub25taWNyb3NvZnQuY29tIiwidXBuIjoiYWRtaW5AWW9ya3RlY2hTb2x1dGlvbnNMdGQub25taWNyb3NvZnQuY29tIiwidXRpIjoiZ2Y5YU1aS3d1VW1UY25CQUl3NHFBUSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19wbCI6ImVuLUdCIn0.YB3-jUL3tLkDo1jCtd7So6_wIv3eTlJjKrZh7_sjhpLljdwLdb-eYOJIMiWS7sQmJnlNsW8ZAerzeEfmfLUb0-XXpZnJFmB4mnJvHB-6ItyOe8qxxMwKJ-w_i23GtmHmEaKZlzmjeX44LX-2XV2azwbRUTj6C4j6bMAdLCKRNteBcge8VRdCayxc-NTTYlKstE8BQg0PJjKg3yk4Tg8Xl35p-bAyasimePJMEhICMGCrwhlOo8gX_JGCOmH7Zljxt1vCn4Iy1VU3gAowxXT4jmr0Kn_NlJBv02urf_aypvQeZY2gHchWclzZGKMq6pqPDTQ0EPw7d2HG5P43_TIidg"

response = requests.post(url, data=data)
access_token = response.json().get('access_token')
headers = {
    'Authorization': f'Bearer {token}'
}
api_url = 'https://api.powerbi.com/v1.0/myorg/reports'  # Example endpoint

response = requests.get(api_url, headers=headers)
reports = response.json()
print(reports)